import type { NextPage } from 'next'
import Head from 'next/head'
import { TodoApp } from '../components/TodoApp'
import styled from 'styled-components';
import { theme } from '../styles';

const Container = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100%;
    min-height: 100vh;
    background-color: ${theme.colors.background};
`;


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <TodoApp />
      </Container>
    </>
  )
}

export default Home
